[tools]
java = "23.0.2"
maven = "3.9.16"

[tasks.install]
run = "mvn dependency:go-offline"

[tasks.lazy]
run = "cargo run --manifest-path ../../../Cargo.toml -- http spring --cwd . --upstream-port 4105 -- mvn spring-boot:run"
